# Give Me Some Credit

Nosso problema é explicitamente prever a probabilidade de uma pessoa enfrentar dificuldades financeiras nos dois anos seguintes.

Primeiro passo é fazer uma instalação das bibliotecas. Elas irão conter funções que nós iremos usar para manipular os dados e verificar a integridade deles para fazermos a análise exploratória de dados. 

**DICA**: você pode ter o modelo mais refinado do mundo, se os dados forem ruins, o modelo não vai conseguir fazer uma boa previsão ;)

In [ ]:
# % é como se estivessemos acessando a máquina no Notebook
%pip install numpy pandas matplotlib

### Recomendação 

Sempre busque ler a documentação dessas bibliotecas. Joga no Google algo como "{nome da biblioteca} documentation" que geralmente vai ser o primeiro link. Lá vai ter, literalmente, TUDO que você precisa saber. Desde primeiros passos até o detalhe de cada parâmetro de cada função. Coisa doida.

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [5]:
df_sample_entry = pd.read_csv("data/sampleEntry.csv")
df_cs_training = pd.read_csv("data/cs-training.csv")

In [ ]:
df_sample_entry.head()

   Id  Probability
0   1     0.080807
1   2     0.040719
2   3     0.011968
3   4     0.067640
4   5     0.108264

In [6]:
df_cs_training.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0